version: "3.9"

services:
  web:
    build: .
    ports:
      - "8082:3000"
    volumes:
      - ".:/app"
    environment:
      NODE_ENV: development
    working_dir: /app
    command: sh -c "npm install && npm start"
